#!/bin/bash

ask_yes_no() {
    while true; do
        read -p "Proceed ? (Y/N) " yn
        case $yn in
            [Yy]* ) return 0;;  # Return 0 for "yes"
            [Nn]* ) return 1;;  # Return 1 for "no"
            * ) echo "Please answer yes or no.";;
        esac
    done
}

r_command() {
command=$1
arg=$2
eval $command $arg
# Check if the command was successful
if [ $? -eq 0 ]; then
  return 0
else
  return 1
fi
}

console_keyboard_font() {
  echo "Setting Console Keyboard Layout to EN...."
  if ask_yes_no; then
    loadkeys en
    
  else
    cmd="loadkeys"
    while true; do
      localectl list-keymaps
      clear
      read -p "Enter the your keyboard-layout : " layout
      if r_command $cmd $layout; then
          break
      else
        echo "Enter a valid input"
        sleep 2
      
      fi
    done
  fi
  echo "Layout Loded...."
  sleep 2
}


check_uefi() {
  inf=cat "/sys/firmware/efi/fw_platform_size" > /dev/null
  if [ $inf==64 ]; then
    echo "System is booted with UEFI....."
  else
    echo "Suystem is booted with LEGACY......" 
  echo "Kindly remember you'r boot, it might be a key for further steps."
  echo "If you are not satisfid then, Kindly Chnage You BOOT."
  sleep 2
  fi
}

check_internet() {
  ping -c 1 8.8.8.8 >> /dev/null
  if [ $? -eq 0 ]; then
    echo "Internet working...."
    sleep 2
  else
    echo "Internet Not Working..."
    echo "Please Connect to a Network , this script need internt connecitom | "
    sleep 2
    exit
  fi
}

time_date() {
  timedatectl set-ntp true
  
  echo "Setting Time Zone to Asia/Calcutta...."
  if ask_yes_no; then
    timedatectl set-timezone Asia/Calcutta
    
  else
  cmdt="timedatectl set-timezone"
    while true; do
        timedatectl lsit-timezones
        clear
        read -p "Enter the your TimeZone : " tmz
        if r_command $cmdt $tmz; then
            break
        else
          echo "Enter a valid input"
          sleep 2
        
        fi
    done
  fi
}

check_uefi
console_keyboard_font
time_date
check_internet
