#!/bin/bash

ask_yes_no() {
    while true; do
        read -p "Proceed ? (Y/N) " yn
        case $yn in
            [Yy]* ) return 0;;  # Return 0 for "yes"
            [Nn]* ) return 1;;  # Return 1 for "no"
            * ) return 0;;
        esac
    done
}

console_keyboard_font() {
  echo "Setting Console Keyboard Layout to EN...."
  if ask_yes_no; then
    loadkeys en
    
  else
    while true; do
      localectl list-keymaps
      clear
      read -p "Enter the your keyboard-layout : " layout
      loadkeys $layout
      if [ $? -eq 0 ]; then
          break
      else
        echo "Enter a valid input"
        sleep 2
      
      fi
    done
  fi
  echo "Layout Loded...."
  sleep 2
  clear
}


check_uefi() {
  if [ -d /sys/firmware/efi ]; then
    echo "System is booted in UEFI mode."
  else
    echo "System is booted in Legacy BIOS mode."
  fi
  echo "Kindly remember you'r boot, it might be a key for further steps."
  echo "If you are not satisfid then, Kindly Chnage You BOOT."
  sleep 2
  clear

}

check_internet() {
  ping -c 1 8.8.8.8 > /dev/null 2>&1
  if [ $? -eq 0 ]; then
    echo "Internet working...."
    sleep 2
  else
    echo "Internet Not Working..."
    echo "Please Connect to a Network , this script need internt connecitom | "
    sleep 2
    exit
  fi
  clear
}

time_date() {
  timedatectl set-ntp true
  
  echo "Setting Time Zone to Asia/Calcutta...."
  if ask_yes_no; then
    timedatectl set-timezone Asia/Calcutta
    
  else
    while true; do
    timedatectl lsit-timezones
    read -p "Enter the your TimeZone : " tmz
    timedatectl set-timezone $tmz
    if [ $? -eq 0 ]; then
        break
    else
        echo "Enter a valid input"
        sleep 2
    fi
    done
  fi
}

check_uefi
console_keyboard_font

clear

time_date
check_internet
