#!/bin/sh

### Run This Script After Running `install-script` ###

if [ -d .zsh-configs ];then
	cp .zsh-configs/.zshrc ~
	cp .zsh-configs/.zshenv ~
else 
	echo "Please change you PWD to dotfiles ( git cloned ) "
	exit 23
fi

echo "Root Password for Installing ZSH"
su - root -c "pacman -S zsh"

cd /home/$USER/.config/zsh/plugin
rm -rf *
clear
git clone https://github.com/zsh-users/zsh-history-substring-search
clear
git clone https://github.com/zsh-users/zsh-syntax-highlighting.git
clear
git clone https://github.com/zsh-users/zsh-autosuggestions

cd /home/$USER/.config/zsh
rm -rf powerlevel10k
clear
git clone --depth=1 https://github.com/romkatv/powerlevel10k.git 
clear

