#! /bin/sh

#pgrep -x sxhkd > /dev/null || sxhkd &


bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xsetroot -cursor_name left_ptr
feh --bg-scale /home/akrit/.config/wallpaper/Dark_5.jpg &
feh --bg-scale /home/akrit/.config/wallpaper/Dark_5.jpg &
/home/akrit/.config/polybar/launch.sh &
dunst &
picom -b &
/home/akrit/.local/bin/system_started_in &
